Department.destroy_all

Department.create(name: 'Aerospace Studies (AERO)', active: true)
Department.create(name: 'Afro-American Studies (AFRO)', active: true)
Department.create(name: 'Allied Health (AHLT)', active: true)
Department.create(name: 'Amer Sign Lang/Eng Interpret (ASL)', active: true)
Department.create(name: 'American Studies (AMST)', active: true)
Department.create(name: 'Anatomy (ANAT)', active: true)
Department.create(name: 'Anesthesiology (ANES)', active: true)
Department.create(name: 'Anthropology (ANTH)', active: true)
Department.create(name: 'Architectural Technology (ART)', active: true)
Department.create(name: 'Astronomy (AST)', active: true)
Department.create(name: 'Biochemistry (BIOC)', active: true)
Department.create(name: 'Biology (BIOL)', active: true)
Department.create(name: 'Biomedical Engineering (BME)', active: true)
Department.create(name: 'Business (BUSG)', active: true)
Department.create(name: 'Business (BUS)', active: true)
Department.create(name: 'Business Evening MBA (BUSN)', active: true)
Department.create(name: 'Business Prof Accountancy (BUPA)', active: true)
Department.create(name: 'Candidate (CAND)', active: true)
Department.create(name: 'Chemistry and Chemical Biology (CHEM)', active: true)
Department.create(name: 'Classical Studies (CL)', active: true)
Department.create(name: 'Classical Studies (CLAS)', active: true)
Department.create(name: 'Communication & Culture (CMCL)', active: true)
Department.create(name: 'Communication & Theatre (COMM)', active: true)
Department.create(name: 'Computer Graphics Technology (CGT)', active: true)
Department.create(name: 'Computer Information Tech (CIT)', active: true)
Department.create(name: 'Computer Science (CM)', active: true)
Department.create(name: 'Computer Science (CSCI)', active: true)
Department.create(name: 'Construction Engr Mgmt Tech (CEMT)', active: true)
Department.create(name: 'Criminal Justice-Coas (CJUS)', active: true)
Department.create(name: 'Dental Assisting (DAST)', active: true)
Department.create(name: 'Dental Auxiliary Education (DAE)', active: true)
Department.create(name: 'Dental Hygiene (DHYG)', active: true)
Department.create(name: 'Dentistry (DENT)', active: true)
Department.create(name: 'East Asian Lang & Culture (EALC)', active: true)
Department.create(name: 'Economics (ECON)', active: true)
Department.create(name: 'Education (EDUC)', active: true)
Department.create(name: 'Electrical & Computer Eng Tech (ECET)', active: true)
Department.create(name: 'Electrical & Computer Engr (ECE)', active: true)
Department.create(name: 'Emergency Medical Services (EMER)', active: true)
Department.create(name: 'Energy Engineering (EEN)', active: true)
Department.create(name: 'Engineering, Freshman (ENGR)', active: true)
Department.create(name: 'English (ENG)', active: true)
Department.create(name: 'Film Studies (FILM)', active: true)
Department.create(name: 'Folklore (FOLK)', active: true)
Department.create(name: 'Foods & Nutrition (FN)', active: true)
Department.create(name: 'Forensic & Investigative Sci (FIS)', active: true)
Department.create(name: 'French (FREN)', active: true)
Department.create(name: 'General Science (SCI)', active: true)
Department.create(name: 'General Studies (GNST)', active: true)
Department.create(name: 'Geography (GEOG)', active: true)
Department.create(name: 'Geology (GEOL)', active: true)
Department.create(name: 'Germanic Languages (GER)', active: true)
Department.create(name: 'Graduate (GRAD)', active: true)
Department.create(name: 'Graduate Medicine (GRDM)', active: true)
Department.create(name: 'Health Information Management (HIM)', active: true)
Department.create(name: 'Health Sciences (HLSC)', active: true)
Department.create(name: 'Health, Phys Ed, & Recreation (HPER)', active: true)
Department.create(name: 'Healthcare Engr Tech Mgmt (HETM)', active: true)
Department.create(name: 'Herron Art (HER)', active: true)
Department.create(name: 'History (HIST)', active: true)
Department.create(name: 'Honors (HON)', active: true)
Department.create(name: 'Industrial Engr Technology (IET)', active: true)
Department.create(name: 'Informatics (INFO)', active: true)
Department.create(name: 'Innovation & Implement Science (IIS)', active: true)
Department.create(name: 'Interior Design (INTR)', active: true)
Department.create(name: 'International Studies (INTL)', active: true)
Department.create(name: 'Journalism & Public Relations (JOUR)', active: true)
Department.create(name: 'Kinesiology (KINE)', active: true)
Department.create(name: 'Labor Studies (LSTU)', active: true)
Department.create(name: 'Languages-General (LG)', active: true)
Department.create(name: 'Latin (LA)', active: true)
Department.create(name: 'Latino Studies (LATS)', active: true)
Department.create(name: 'Law (LAW)', active: true)
Department.create(name: 'Liberal Arts and Mgmt Program (LAMP)', active: true)
Department.create(name: 'Library & Information Science (LIS)', active: true)
Department.create(name: 'Linguistics (LING)', active: true)
Department.create(name: 'Mathematics (MATH)', active: true)
Department.create(name: 'Mathematics (MT)', active: true)
Department.create(name: 'Mechanical Engineering (ME)', active: true)
Department.create(name: 'Mechanical Engr Tech (MET)', active: true)
Department.create(name: 'Medical Genetics (MGEN)', active: true)
Department.create(name: 'Medical Humanities & Hlth Stud (MHHS)', active: true)
Department.create(name: 'Medical Neurobiology (MNEU)', active: true)
Department.create(name: 'Medical Sciences (MSCI)', active: true)
Department.create(name: 'Medicine (MED)', active: true)
Department.create(name: 'Medicine Registrations (MEDC)', active: true)
Department.create(name: 'Microbiology (MICR)', active: true)
Department.create(name: 'Military (MIL)', active: true)
Department.create(name: 'Motorsports Engineering (MSTE)', active: true)
Department.create(name: 'Motorsports Studies (MSPT)', active: true)
Department.create(name: 'Museum Studies (MSTD)', active: true)
Department.create(name: 'Music (MUS)', active: true)
Department.create(name: 'Music (MU)', active: true)
Department.create(name: 'National Student Exchange Prg (NSXP)', active: true)
Department.create(name: 'Native Amercn & Indigenous St (NAIS)', active: true)
Department.create(name: 'Near Eastern Lang & Cult (NELC)', active: true)
Department.create(name: 'New Media (NEWM)', active: true)
Department.create(name: 'Nursing (NURS)', active: true)
Department.create(name: 'Nutrition and Dietetics (NTRD)', active: true)
Department.create(name: 'Occupational Therapy (OCTH)', active: true)
Department.create(name: 'Org Leadership & Supervision (OLS)', active: true)
Department.create(name: 'Overseas Studies (OVST)', active: true)
Department.create(name: 'Pathology (PATH)', active: true)
Department.create(name: 'Pharmacology (PHAR)', active: true)
Department.create(name: 'Philanthropic Studies (PHST)', active: true)
Department.create(name: 'Philosophy (PHIL)', active: true)
Department.create(name: 'Physical Education (PE)', active: true)
Department.create(name: 'Physical Therapy (PTHR)', active: true)
Department.create(name: 'Physician Assistant (MPAS)', active: true)
Department.create(name: 'Physics (PH)', active: true)
Department.create(name: 'Physics (PHYS)', active: true)
Department.create(name: 'Physiology (PHSL)', active: true)
Department.create(name: 'Political Science (POLS)', active: true)
Department.create(name: 'Program for Intensive English (PIE)', active: true)
Department.create(name: 'Psychology (PSY)', active: true)
Department.create(name: 'Public And Envir Affairs (SPEA)', active: true)
Department.create(name: 'Public Health (PBHL)', active: true)
Department.create(name: 'Pulmonary & Critical Care Med (PULM)', active: true)
Department.create(name: 'Radiation Oncology (RAON)', active: true)
Department.create(name: 'Radiologic Sciences (RADS)', active: true)
Department.create(name: 'Radiology (RADI)', active: true)
Department.create(name: 'Religion (RL)', active: true)
Department.create(name: 'Religious Studies (REL)', active: true)
Department.create(name: 'School Of Liberal Arts (SLA)', active: true)
Department.create(name: 'Social Work (SWK)', active: true)
Department.create(name: 'Sociology (SOC)', active: true)
Department.create(name: 'Spanish (SPAN)', active: true)
Department.create(name: 'Statistics (STAT)', active: true)
Department.create(name: 'Technical Communications (TCM)', active: true)
Department.create(name: 'Technology (TECH)', active: true)
Department.create(name: 'Theatre (TE)', active: true)
Department.create(name: 'Tourism Conv & Event Mgmt (TCEM)', active: true)
Department.create(name: 'Tourism, Event & Sport Mgmt (TESM)', active: true)
Department.create(name: 'University College (UCOL)', active: true)
Department.create(name: 'Women\'s Studies (WOST)', active: true)
Department.create(name: 'World Languages and Cultures (WLAC)', active: true)
