default: &default
  :ldap:
    :host: ads.university.edu
    :username: username
    :password: password
    :authbase: 'ou=group,ou=accounts,dc=ads,dc=university,dc=edu'
    :treebase: 'ou=accounts,dc=ads,dc=university,dc=edu'

  # Roles with the ldap groups that should be assigned to them.
  :roles:
    :instructor:
      - UNIV-FACULTY
      - LIB-Admins
    :admin:
      - LIB-OPS

  # Email settings
  :email:
    :default_from: 'noreply@univeristy.edu'
    :daily_to: 'user@university.edu'
    :library_from:
      'University Library': library@university.edu
      'Art Library': art@university.edu

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
