default: &default
  :ldap:
    :host: ads.university.edu
    :username: username
    :password: password
    :authbase: 'ou=group,ou=accounts,dc=ads,dc=university,dc=edu'
    :treebase: 'ou=accounts,dc=ads,dc=university,dc=edu'

  # Roles with the ldap groups that should be assigned to them.
  :roles:
    :instructor: ['UNIV-FACULTY','LIB-Admins']
    :admin: ['LIB-OPS']

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
