default: &default
  # LDAP used for adding users to roles.
  :ldap:
    :host: ads.university.edu
    :user: username
    :password: password
    :authbase: 'ou=group,ou=accounts,dc=ads,dc=university,dc=edu'
    :treebase: 'ou=accounts,dc=ads,dc=university,dc=edu'

  # Roles with the ldap groups that should be assigned to them.
  :roles:
    :instructor:
      - UNIV-FACULTY
      - LIB-Admins
    :admin:
      - LIB-OPS

  # Email settings
  :email:
    :default_from: 'noreply@library.edu'
    :daily_to: 'someone@library.edu'

  # Production secret must be set in config file.
  :secret_key: 12345678900987654321

  # Production Database settings must be in config file.
  :db:
    :adapter: mysql2
    :host: localhost
    :database: db_name
    :username: db_username
    :password: db_password

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  :secret_key: 12345678900987654321
  :db:
    :adapter: mysql2
    :host: localhost
    :database: db_name
    :username: db_username
    :password: db_password
